[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Opcional: redirige /api/* a las funciones (si quieres rutas bonitas)
#[[redirects]]
#  from = "/api/state-save"
#  to   = "/.netlify/functions/state-save"
#  status = 200
#[[redirects]]
#  from = "/api/state-get"
#  to   = "/.netlify/functions/state-get"
#  status = 200

# Seguridad mínima (ajústalo si usas recursos de terceros)
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
