[build]
  publish = "."
  functions = "netlify/functions"

  # Node usado en build (y por defecto en Functions si no indicas otra cosa)
  [build.environment]
    NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
